name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Build and test
      run: |
        for file in $(find src -type f -name main.cpp); do
            name=$(basename $(dirname "$file"))
            mkdir -p "build/$name"
            echo "Compiling $file -> build/$name/$name"
            g++ -std=c++17 -Wall -Werror "$file" -o "build/$name/$name"
        done

        
